version: '3.8'

services:
  rabbitmq_server:
    image: rabbitmq:3.13-management
    hostname: my-rabbit
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_net
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rb_data:/var/lib/rabbitmq/mnesia/"

networks:
  app_net:

volumes:
  rb_data:
    driver: local